### ISSUE TITLE
Collapsed input fields

### ISSUE THREAD

**Issue by dajbassow** [auri/auri#41]
Input fields for password, confirm password and ssh are collapsed by default when you want to set your credentials. 
To recreate the issue make a new account request, wait for validation from an admin and the e-mail with the link "set your credentials"

https://github.com/auri/auri/blob/master/templates/credentials-reset-data-collection.plush.html

**Comment by artem-sidorenko** [comment]
@dajbassow thanks for raising this issue :-) It's again because of bootstrap 5 upgrade and is going to be fixed by #42
